### ISSUE TITLE
切换到本软件，焦点自动到ISBN输入框，并在输入框提示粘贴选项

### ISSUE THREAD

**Issue by zoshl** [Hellohistory/EbookDataTools#4]

**Comment by Hellohistory** [comment]
不知道您可不可以说的更具体一些，我有一点不明白

**Comment by zoshl** [comment]
就是软件从后台和刚打开软件，每次都要点击ISBN输入框才可以输入，能不能改成打开软件或后台切换到软件，输入法焦点自动定位到ISBN输入框，并在输入框显示右键粘贴，删除，复制能功能。后台切换到本软件，自动全选ISBN号，并弹出复制粘贴，删除右键功能，

**Comment by zoshl** [comment]
如果不好实现，那就在isbn输入框加右键点击菜单，显示复制，粘贴、全选和删除菜单
